version: "3"
services:
  storybook:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    ports:
      - "9009:9009"
    privileged: true
    command: "npm run storybook"
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    ports:
      - "3000:3000"
    privileged: true
    environment:
      - REACT_APP_ASSET_REGISTER_API_URL=http://localhost:5000/
      - REACT_APP_DISPLAY_MAPS=yes
      - REACT_APP_MAPS_API_KEY=${MAP_API_KEY}
