version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.12.0

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy_staging:
    executor: node
    steps:
      - checkout
      - run: bin/deploy.sh staging

  deploy_production:
    executor: node
    steps:
      - checkout
      - run: bin/deploy.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - hold
